# Oh-my-zsh base configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git) 
source $ZSH/oh-my-zsh.sh

# macOS specific sources
if [[ -f /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
    source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    bindkey '^ ' autosuggest-accept
elif command -v brew >/dev/null 2>&1; then
    source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    bindkey '^ ' autosuggest-accept
fi

eval "$(zoxide init zsh)"

# Source common configurations
source "$HOME/dotfiles/shared/zsh/common"

# Source local overwrites that are not source-controlled
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

# pnpm
export PNPM_HOME="/Users/hassieb/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
