# Oh-my-zsh base configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="gentoo"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Source common configurations
source "$HOME/dotfiles/shared/zsh/common"

# Source local overwrites that are not source-controlled
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
